const express=require('express'); const http=require('http'); const {Server}=require('socket.io');
const app=express(), server=http.createServer(app), io=new Server(server); app.use(express.static('public'));
const PORT=process.env.PORT||3000, MIN_BID=160, MAX_BID=250;
const SUITS=['S','H','D','C'], RANKS=['A','K','Q','J','10','9','8','7','6','5','4','3','2'];
const rooms=new Map(); const rankValue=r=>13-RANKS.indexOf(r);
function deck(){let d=[];for(const s of SUITS)for(const r of RANKS){if(r==='2'&&(s==='C'||s==='D'))continue;d.push({s,r,id:r+s});}return d;}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function pts(c){if(['A','K','Q','J','10'].includes(c.r))return 10;if(c.r==='5')return 5;if(c.r==='3'&&c.s==='S')return 30;return 0;}
function next(i,n=1){return (i+n)%5;} // seating array is anticlockwise play order
function roomCode(){let x;do{x=Math.random().toString(36).slice(2,6).toUpperCase()}while(rooms.has(x));return x;}
function publicState(g,viewer){const me=g.players.findIndex(p=>p.id===viewer);return {code:g.code,phase:g.phase,players:g.players.map((p,i)=>({name:p.name,seat:i,score:p.score,handCount:p.hand.length,team:g.teams?g.teams[i]:null})),me,startBidder:g.startBidder,bid:g.bid,incumbent:g.incumbent,challenger:g.challenger,bidTurn:g.bidTurn,bidAction:g.bidAction,bidder:g.bidder,trump:g.trump,calls:g.calls,leader:g.leader,turn:g.turn,trick:g.trick,teamPoints:g.teamPoints,dealNo:g.dealNo,lastResult:g.lastResult,hand:me>=0?g.players[me].hand:[],legal:me>=0?legalCards(g,me):[],canStart:g.phase==='lobby'&&g.players.length===5&&g.players[0]?.id===viewer};}
function emit(g){for(const p of g.players)io.to(p.id).emit('state',publicState(g,p.id));}
function newDeal(g){g.dealNo++; const d=shuffle(deck());g.players.forEach((p,i)=>p.hand=d.slice(i*10,i*10+10).sort((a,b)=>SUITS.indexOf(a.s)-SUITS.indexOf(b.s)||RANKS.indexOf(a.r)-RANKS.indexOf(b.r)));g.phase='bidding';g.bid=null;g.incumbent=null;g.challenger=null;g.bidTurn=g.startBidder;g.bidAction='open';g.passed=new Set();g.bidder=null;g.trump=null;g.calls=[];g.teams=null;g.trick=[];g.leader=null;g.turn=null;g.teamPoints=[0,0];g.lastResult=null;emit(g);}
function advanceOpening(g,idx){g.passed.add(idx);let j=next(idx);while(g.passed.has(j)&&j!==idx)j=next(j);if(g.passed.size===5){g.lastResult={text:'All five players passed. Deal abandoned.'};g.startBidder=next(g.startBidder);return newDeal(g);}g.bidTurn=j;g.bidAction='open';}
function nextUnpassedAfter(g,idx){let j=next(idx);while(g.passed.has(j)&&j!==idx)j=next(j);return j;}
function startChallenge(g){const c=nextUnpassedAfter(g,g.incumbent);if(c===g.incumbent){return winBid(g,g.incumbent);}g.challenger=c;g.bidTurn=c;g.bidAction='raise';}
function winBid(g,i){g.bidder=i;g.phase='contract';g.bidTurn=null;g.challenger=null;}
function handlePass(g,i){if(g.phase!=='bidding'||g.bidTurn!==i)return;if(g.bidAction==='open'){advanceOpening(g,i);return;}if(g.bidAction==='raise'){g.passed.add(i);g.challenger=null;if(g.passed.size===4)return winBid(g,g.incumbent);startChallenge(g);return;}if(g.bidAction==='respond'){g.passed.add(i);g.incumbent=g.challenger;g.challenger=null;if(g.passed.size===4)return winBid(g,g.incumbent);startChallenge(g);}}
function handleBid(g,i,amount){amount=Number(amount);if(g.phase!=='bidding'||g.bidTurn!==i||amount%5||amount<MIN_BID||amount>MAX_BID)return;if(g.bidAction==='open'){if(amount!==MIN_BID)return;g.bid=amount;g.incumbent=i;startChallenge(g);return;}if(g.bidAction==='raise'){if(amount<=g.bid)return;g.bid=amount;g.bidTurn=g.incumbent;g.bidAction='respond';return;}}
function stay(g,i){if(g.phase!=='bidding'||g.bidTurn!==i||g.bidAction!=='respond'||i!==g.incumbent)return;g.bidTurn=g.challenger;g.bidAction='raise';}
function legalCards(g,i){if(g.phase!=='play'||g.turn!==i)return[];const h=g.players[i].hand;if(!g.trick.length)return h.map(c=>c.id);const suit=g.trick[0].card.s;const follow=h.filter(c=>c.s===suit);return (follow.length?follow:h).map(c=>c.id);}
function trickWinner(g){const lead=g.trick[0].card.s;let candidates=g.trick.filter(x=>x.card.s===g.trump);if(!candidates.length)candidates=g.trick.filter(x=>x.card.s===lead);return candidates.reduce((a,b)=>rankValue(a.card.r)>rankValue(b.card.r)?a:b).player;}
function finishDeal(g){const bidderTeam=g.teams.map((t,i)=>t==='bidder'?i:null).filter(x=>x!==null);const opp=g.teams.map((t,i)=>t==='opponent'?i:null).filter(x=>x!==null);const bp=g.teamPoints[0], op=g.teamPoints[1], ok=bp>=g.bid; if(ok){for(const i of bidderTeam)g.players[i].score+=i===g.bidder?g.bid+50:g.bid;}else{g.players[g.bidder].score-=50;for(const i of opp)g.players[i].score+=op;}g.lastResult={text:ok?`Contract made: ${bp} ≥ ${g.bid}.`:`Contract failed: ${bp} < ${g.bid}. Opponents captured ${op}.`,bidderPoints:bp,opponentPoints:op,success:ok};g.phase='result';g.startBidder=next(g.startBidder);emit(g);}
function play(g,i,id){if(!legalCards(g,i).includes(id))return;const p=g.players[i], k=p.hand.findIndex(c=>c.id===id), card=p.hand.splice(k,1)[0];g.trick.push({player:i,card});if(g.trick.length<5){g.turn=next(i);emit(g);return;}const w=trickWinner(g), tp=g.trick.reduce((s,x)=>s+pts(x.card),0);g.teamPoints[g.teams[w]==='bidder'?0:1]+=tp;g.leader=w;g.turn=w;g.lastTrick=g.trick;g.trick=[];if(g.players.every(p=>!p.hand.length))return finishDeal(g);emit(g);}
io.on('connection',s=>{s.on('create',name=>{const code=roomCode(),g={code,players:[{id:s.id,name:String(name||'Player 1').slice(0,20),score:0,hand:[]}],phase:'lobby',startBidder:0,dealNo:0};rooms.set(code,g);s.join(code);emit(g);});s.on('join',({code,name})=>{const g=rooms.get(String(code).toUpperCase());if(!g||g.phase!=='lobby'||g.players.length>=5)return s.emit('errorMsg','Room unavailable.');g.players.push({id:s.id,name:String(name||`Player ${g.players.length+1}`).slice(0,20),score:0,hand:[]});s.join(g.code);emit(g);});s.on('start',()=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(g&&g.players[0].id===s.id&&g.players.length===5)newDeal(g);});s.on('pass',()=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(!g)return;const i=g.players.findIndex(p=>p.id===s.id);handlePass(g,i);emit(g);});s.on('bid',a=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(!g)return;const i=g.players.findIndex(p=>p.id===s.id);handleBid(g,i,a);emit(g);});s.on('stay',()=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(!g)return;stay(g,g.players.findIndex(p=>p.id===s.id));emit(g);});s.on('contract',({calls,trump})=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(!g||g.phase!=='contract'||g.players[g.bidder].id!==s.id||!SUITS.includes(trump)||!Array.isArray(calls)||calls.length!==2||calls[0]===calls[1])return;const own=new Set(g.players[g.bidder].hand.map(c=>c.id));if(calls.some(x=>own.has(x)||!deck().some(c=>c.id===x)))return;g.calls=calls;g.trump=trump;const holders=calls.map(id=>g.players.findIndex(p=>p.hand.some(c=>c.id===id)));const team=new Set([g.bidder,...holders]);g.teams=g.players.map((_,i)=>team.has(i)?'bidder':'opponent');g.phase='play';g.leader=next(g.bidder);g.turn=g.leader;emit(g);});s.on('play',id=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(g)play(g,g.players.findIndex(p=>p.id===s.id),id);});s.on('nextDeal',()=>{const g=[...rooms.values()].find(r=>r.players.some(p=>p.id===s.id));if(g&&g.phase==='result')newDeal(g);});});
server.listen(PORT,()=>console.log(`250 running on http://localhost:${PORT}`));
